In [4]:
#a funcao arrange cria um vetor contendo uma progressao aritimetica a partir de um intervalo - start, stop, step
import numpy as np
vetor2 = np.arange(0., 4.5, .5)

In [5]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [6]:
#formato de um array
np.shape(vetor2)

(9,)

In [7]:
#dtype diz o tipo do vetor
print(vetor2.dtype)

float64


In [10]:
x = np.arange(1, 10, 0.25)

In [11]:
print(x
     )

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [12]:
#pode criar um vetor com 0 usando a funcao zeros
z = np.zeros(10)

In [13]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#funcao eye retorna 1 na posicao diagonal e 0 nas demais
z = np.eye(3)

In [15]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#os valores passados como parametro formam uma diagonal usando a funcao diag
d = np.diag(np.array([1,2,3,4]))

In [17]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#array de numeros complexos
c = np.array([1.+ 2j, 3+4j, 5+6j])

In [22]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [23]:
#array de valores booleanos
e = np.array([True, False, False, True])

In [24]:
e

array([ True, False, False,  True])

In [25]:
#array de strings
s = np.array(['Python', 'R', 'DataScience'])

In [26]:
s

array(['Python', 'R', 'DataScience'], dtype='<U11')

In [27]:
#o metodo linspace(linearly spaced vector) retorna o numero de valores 
#igualmente distribuidos no intervalo especifico
np.linspace(0 , 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
print(np.linspace(0, 10 , 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [29]:
print(np.logspace(0, 5 , 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [31]:
#Criando matrizes
matriz = np.array([[1,2,3],[4,5,6]])

In [32]:
matriz


array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#usando o shape como atributo
matriz.shape

(2, 3)

In [34]:
#criando uma matriz 2x3 apenas com o numero 1 usando o metodo ones
matriz = np.ones((2,3))

In [35]:
matriz


array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
#criando uma matriz a partir de uma lista
lista = [[15,16,18],[65,87,98],[74,54,12]]

In [37]:
lista

[[15, 16, 18], [65, 87, 98], [74, 54, 12]]

In [38]:
# a funcao matrix cria uma matriz a partir de uma sequencia
matriz2 = np.matrix(lista)

In [39]:
matriz2

matrix([[15, 16, 18],
        [65, 87, 98],
        [74, 54, 12]])

In [40]:
#mostrar o tipo da atriz
type(matriz2)

numpy.matrixlib.defmatrix.matrix

In [42]:
#usando o shape como metodo para mostrar seu formato
np.shape(matriz2)

(3, 3)

In [43]:
#mostrar tamando do item da matriz
matriz2.itemsize

8

In [44]:
#mostrar numeros de bytes da matriz
matriz2.nbytes

72

In [45]:
#mostrando apenas uma linha e coluna especifica
matriz2[2,1]

54

In [46]:
#alterar o elemento da matriz
matriz2[1,2] = 50

In [47]:
matriz2

matrix([[15, 16, 18],
        [65, 87, 50],
        [74, 54, 12]])

In [51]:
#ddefinindo tipo de dados manual ou deixando o numpy definir
x = np.array([1, 5]) # o numpy vai definir
y = np.array([5.2, 7.0]) # o numpy vai definir
z = np.array([5.0, 8 ], dtype=np.float64) # inserimos manual o tipo de array

In [52]:
print(z.dtype, x.dtype, y.dtype)

float64 int64 float64
